# Numpy 101

The goal of this challenge is to get familiar with the Numpy library, manipulate multidimensional arrays and apply some linear algebra operations without using `for` loops.

💡 Do not forget to keep the [Numpy Cheat Sheet](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf) closed during this challenge.

In [1]:
import numpy as np # Run this cell!

---

**Q1** - Create a null vector (i.e. with only zeros `0`) of size 10 and assign it to a variable named `ten_zeros`. 

It should look like this:

```
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
```

<details>
    <summary>🆘 Hint</summary>
    <p>Have a look at <a href="https://numpy.org/devdocs/reference/generated/numpy.zeros.html"><code>numpy.zeros</code></a></p>
</details>

In [2]:
ten_zeros = np.zeros(10)
ten_zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

---

**Q2** - Create a vector with values from 5 to 10 and assign it to a variable named `five_to_ten`.

It should look like this:

```
array([ 5,  6,  7,  8,  9, 10])
```

<details>
    <summary>🆘 Hint</summary>
    <p>Have a look at <a href="https://numpy.org/devdocs/reference/generated/numpy.arange.html"><code>numpy.arange</code></a></p>
</details>

In [3]:
five_to_ten = np.arange(5, 11)
five_to_ten

array([ 5,  6,  7,  8,  9, 10])

---

**Q3** - Create the following matrix as a NumPy `ndarray` and assign it to a variable named `A`:

$
A = 
\begin{pmatrix}
5 & 9 & 7\\
1 & 0 & 3
\end{pmatrix}
$

<br>
<details>
    <summary>🆘 Hint</summary>
    <p>Have a look at <a href="https://numpy.org/devdocs/reference/generated/numpy.array.html"><code>numpy.array</code></a></p>
    <p>Checkout more about the relationship between<a href="https://stackoverflow.com/questions/15879315/what-is-the-difference-between-ndarray-and-array-in-numpy"><code>numpy.array and numpy.ndarray</code></a></p>
</details>

In [4]:
A = np.array([[5, 9, 7], [1, 0, 3]])
A

array([[5, 9, 7],
       [1, 0, 3]])

---
**Q4** - Create the following matrix without using the `np.array()` constructor and assign it to a variable named `B`:

$
B = 
\begin{pmatrix}
1 & 1\\
1 & 1
\end{pmatrix}
$

In [5]:
B = np.ones((2, 2), dtype=int)
B

array([[1, 1],
       [1, 1]])

---

**Q5** - Create a vector of 20 elements evenly spaced between `-1` and `1` and assign it to a variable named `lin_twenty`.

It should look like this:

```
array([-1.        , -0.89473684, -0.78947368, -0.68421053, -0.57894737,
       -0.47368421, -0.36842105, -0.26315789, -0.15789474, -0.05263158,
        0.05263158,  0.15789474,  0.26315789,  0.36842105,  0.47368421,
        0.57894737,  0.68421053,  0.78947368,  0.89473684,  1.        ])
```

<details>
    <summary>🆘 Hint</summary>
    <p>Have a look at <a href="https://numpy.org/devdocs/reference/generated/numpy.linspace.html"><code>numpy.linspace</code></a></p>
</details>

In [6]:
lin_twenty = np.linspace(-1, 1, 20)
lin_twenty

array([-1.        , -0.89473684, -0.78947368, -0.68421053, -0.57894737,
       -0.47368421, -0.36842105, -0.26315789, -0.15789474, -0.05263158,
        0.05263158,  0.15789474,  0.26315789,  0.36842105,  0.47368421,
        0.57894737,  0.68421053,  0.78947368,  0.89473684,  1.        ])

---

**Q6** - Create a 3x3 identity matrix and assign it to a variable named `C`:

$
C = 
\begin{pmatrix}
1 & 0 & 0\\
0 & 1 & 0\\
0 & 0 & 1
\end{pmatrix}
$

<br>

<details>
    <summary>🆘 Hint</summary>
    <p>Have a look at <a href="https://numpy.org/devdocs/reference/generated/numpy.eye.html"><code>numpy.eye</code></a></p>
</details>

In [7]:
C = np.eye(3, dtype="int")
C

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

---

**Q7** - Create the following `ndarray` and assign it to a variable named `D`:  

$
D = 
\begin{pmatrix}
2 & 9 & 7 & 3 & 1 & 5
\end{pmatrix}
$

Reshape `D` into a 2x3 matrix and assign it to a variable named `E`:

$
E = 
\begin{pmatrix}
2 & 9 & 7\\
3 & 1 & 5
\end{pmatrix}
$

<br>

<details>
    <summary>🆘 Hint</summary>
    <p>Have a look at <a href="https://numpy.org/devdocs/reference/generated/numpy.reshape.html"><code>numpy.reshape</code></a></p>
</details>

In [8]:
D = np.array([2, 9, 7, 3, 1, 5])
E = D.reshape(2, 3)
E

array([[2, 9, 7],
       [3, 1, 5]])

---

**Q8**: Select the second column of this `ndarray` `F`, reshape it as an `ndarray` of 4 lines and 1 column and assign it to a variable named `reshaped_F`:

$
reshaped\_F = 
\begin{pmatrix}
0.?\\
0.?\\
0.?\\
0.?\\
\end{pmatrix}
$

In [9]:
F = np.random.random((4, 5))
print(F)

[[0.23475139 0.57206328 0.72484416 0.43472544 0.72409432]
 [0.94271486 0.94895558 0.91120499 0.67960449 0.06427326]
 [0.50183264 0.81921916 0.75742122 0.87029271 0.74713651]
 [0.09199445 0.36542369 0.78357495 0.42714697 0.07217243]]


In [10]:
reshaped_F = F[:, 1].reshape(4, 1)
reshaped_F

array([[0.57206328],
       [0.94895558],
       [0.81921916],
       [0.36542369]])

---

**Q9** - Compute the sum of matrixes `G` and `H` and store the result into a variable `gh_sum`:

$
G = 
\begin{pmatrix}
0 & 4\\
-4 & -3\\
1 & 1
\end{pmatrix}
$

$
H =
\begin{pmatrix}
0 & 1\\
1 & -1\\
2 & 3
\end{pmatrix}
$

$
G + H = ?
$


In [11]:
# Here we demonstrate two different approaches to creating a (3,2) Matrix
G = np.array([0, 4, -4, -3, 1, 1]).reshape(3, 2)
print('G: \n', G)
H = np.array([[0, 1], [1, -1], [2, 3]])
print('H: \n', H)

G: 
 [[ 0  4]
 [-4 -3]
 [ 1  1]]
H: 
 [[ 0  1]
 [ 1 -1]
 [ 2  3]]


In [12]:
gh_sum = G + H
gh_sum

array([[ 0,  5],
       [-3, -4],
       [ 3,  4]])

## Check your code!

Run the cell below to check your code:

In [13]:
from nbresult import ChallengeResult

result = ChallengeResult('numpy',
    ten=ten_zeros,
    from_five=five_to_ten,
    A=A,
    B=B,
    lin_twenty=lin_twenty,
    C=C,
    E=E,
    F=F,
    reshaped_F=reshaped_F,
    gh_sum=gh_sum
)
result.write()
print(result.check())


============================= test session starts ==============================
platform darwin -- Python 3.10.6, pytest-8.3.4, pluggy-1.5.0 -- /Users/bouchrakostet/.pyenv/versions/3.10.6/envs/lewagon/bin/python
cachedir: .pytest_cache
rootdir: /Users/bouchrakostet/code/lewagon/02-Data-Toolkit/01-Data-Analysis/data-numpy/tests
plugins: asyncio-0.19.0, anyio-4.8.0, typeguard-4.4.2
asyncio: mode=strict
collecting ... collected 5 items

test_numpy.py::TestNumpy::test_advanced_matrixes_manipulation PASSED     [ 20%]
test_numpy.py::TestNumpy::test_linear_twenty_vector_creation PASSED      [ 40%]
test_numpy.py::TestNumpy::test_matrixes_creation_and_reshaping PASSED    [ 60%]
test_numpy.py::TestNumpy::test_ndarrays_creation PASSED                  [ 80%]
test_numpy.py::TestNumpy::test_vectors_creation PASSED                   [100%]

============================== 5 passed in 0.10s ===============================


💯 You can commit your code:

git add tests/numpy.pickle

git commit -m 'Comp